# Generated by Django 6.0 on 2026-01-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, null=True)),
                ('published_at', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bookmark', models.TextField(blank=True, null=True)),
                ('choices', models.CharField(blank=True, choices=[('Wish to', 'wish to'), ('Read', 'read'), ('Favourites', 'favourites')])),
            ],
        ),
    ]
