# Generated by Django 6.0 on 2026-01-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklibrary',
            name='choices',
            field=models.CharField(blank=True, choices=[('Wish to', 'wish to'), ('Read', 'read'), ('Favourites', 'favourites')], default='read'),
        ),
    ]
