# Generated by Django 6.0 on 2026-01-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booklibrary_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklibrary',
            name='choices',
            field=models.CharField(blank=True, choices=[('wish to', 'Wish to'), ('read', 'Read'), ('favourites', 'Favourites')], default='read'),
        ),
    ]
